<a href="https://colab.research.google.com/github/HaripriyaVennam/Neural-Networks-and-Deep-Learning/blob/main/Week2/ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Define the Employee class
class Employee:
    # data member to count the number of employees
    employee_count = 0

    # Constructor to initialize the employee's details like name, family, salary, department
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1  # Increment employee count when a new object is created

    # Method to calculate the average salary of employees
    @staticmethod
    def average_salary(employee_list):
        total_salary = sum(emp.salary for emp in employee_list)
        return total_salary / len(employee_list) if employee_list else 0

# Define the FulltimeEmployee class, inheriting from Employee class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        # Use the constructor of the parent class
        super().__init__(name, family, salary, department)

# Main function
def main():
    # Create instances of Employee
    emp1 = Employee("Ria", "Sharma", 70000, "HR")
    emp2 = Employee("Prem", "Kiran", 80000, "Finance")

    # Create instances of FulltimeEmployee
    fe1 = FulltimeEmployee("Sai", "Kumar", 90000, "Doctor")

    # List of all employees
    all_employees = [emp1, emp2, fe1]

    # Print details of each employee
    print("Employee Details:")
    for emp in all_employees:
        print(f"Name: {emp.name}, Family: {emp.family}, Salary: {emp.salary}, Department: {emp.department}")

    # Print total number of employees
    print(f"\nTotal number of employees: {Employee.employee_count}")

    # Calculate and print the average salary
    avg_salary = Employee.average_salary(all_employees)
    print(f"Average salary of employees: {avg_salary:.2f}")

# Run the main function
if __name__ == "__main__":
    main()


Employee Details:
Name: Ria, Family: Sharma, Salary: 70000, Department: HR
Name: Prem, Family: Kiran, Salary: 80000, Department: Finance
Name: Sai, Family: Kumar, Salary: 90000, Department: Doctor

Total number of employees: 3
Average salary of employees: 80000.00


In [2]:
import numpy as np

# Step 1: Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Step 2: Reshape the array to a 4x5 matrix
matrix = random_vector.reshape(4, 5)

# Print the matrix before modification
print("Original Matrix:\n", matrix)

# Step 3: Replace the maximum value in each row with 0 (without using a for loop)
# Find the indices of the maximum value in each row
max_indices = np.argmax(matrix, axis=1)

# Use advanced indexing to set the maximum values to 0
matrix[np.arange(matrix.shape[0]), max_indices] = 0

# Print the resulting matrix
print("Modified Matrix:\n", matrix)


Original Matrix:
 [[12.81552882 17.43218139 18.08612068  2.36754914 19.50334951]
 [ 2.92515887  2.22675603 19.19909043 19.76961692 17.34315546]
 [ 2.91834354 12.98322743 15.54948475  1.23255186 17.00892621]
 [ 2.91730177  9.42467147  8.32388451  6.16689234  6.81599094]]
Modified Matrix:
 [[12.81552882 17.43218139 18.08612068  2.36754914  0.        ]
 [ 2.92515887  2.22675603 19.19909043  0.         17.34315546]
 [ 2.91834354 12.98322743 15.54948475  1.23255186  0.        ]
 [ 2.91730177  0.          8.32388451  6.16689234  6.81599094]]


https://drive.google.com/file/d/1b5e1U-IquLRa8XrxBdO6uAqWvHh64Ia8/view?usp=drive_link